<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class SIR_LEADS2_VU_KASTLE extends Model
{
    use HasFactory;
    protected $connection = 'oracle';
    protected $table = 'SIR_LEADS2_VU_KASTLE';
    public $timestamps = false;
    protected $primaryKey = 'LEAD_ID';
    protected $fillable = [
        'LEAD_ID',
        'FNAME',
        'PHONE1',
        'CRMNATID',
        'CRMDOB',
        'CITY_ID',
        'PROFESSION_ID',
        'ACC_PROFESSION',
        'SALARYCAT_ID',
        'ACC_SALARY_CAT',
        'SALARYTYPE_ID',
        'ACC_SALARY_TYPE',
        'SALARY',
        'SALARYDEDUCTION',
        'SALARY_BANK_ID',
        'ACC_BANK',
        'ACC_SOURCE',
        'ACC_CHANNEL',
        'ACC_CREATED_BY',
        'PRODUCT_TYPE_ID',
        'PRODUCT_TYPE',
        'PROSPECT_STATUS_ID',
        'PROSPECT_STATUS',
        'SOURCE_ID',
        'CHANNEL_ID',
        'PREF_CALL_TIME',
        'CREATED_BY',
        'CREATION_DATE',
        'ASSIGN_BY',
        'ASSIGNMENT_TO_ID',
        'ASSIGNMENT_NOTE',
        'ASSIGNMENT_STATUS_DATE',
        'MODIFIED_DATE',
        'APP_ID',
        'FULL_NAME',
        'MOBILE',
        'NATID',
        'NATID_EXPIRY_DATE',
        'EMAIL_ADDRESS',
        'LEADCF69',
        'HOUSE_ALLOWANCE',
        'OTHER_ALLOWANCE',
        'SOCIAL_STATUS',
        'SOCIAL_STATUS_V',
        'SOCIAL_STATUS_KASTLE',
        'DOB',
        'RDOB',
        'EMPLOYER_NAME',
        'EMPLOYER_CITY',
        'EMPLOYER_CITY_V',
        'EMPLOYER_CITY_KASTLE',
        'EMPLOYER_ADDRESS',
        'OFFICE_PHONE',
        'EMPLOYER_TYPE',
        'EMPLOYER_TYPE_V',
        'EMPLOYER_TYPE_KASTLE',
        'EMPLOYMENT_TENNURE',
        'EMPLOYMENT_TENNURE_Y',
        'GROSS_SALARY',
        'DEDUCTION_VALUE',
        'APPLICATION_CREATION_DATE',
        'HOUSE_EXPENSE',
        'HOUSING_TYPE',
        'HOUSING_TYPE_V',
        'HOUSING_OWNERSHIP',
        'HOUSING_OWNERSHIP_V',
        'HOUSING_OWNERSHIP_KASTLE',
        'MONTHLY_RENT',
        'NO_OF_DEPENDENT',
        'NO_OF_DOMESTIC_WORKER',
        'DOMESTIC_WORKER_SALARY',
        'INVOICES',
        'INSURANCE_VALUE',
        'NUMBER_OF_DEPENDENT_IN_PRIVATE_SCHOOL',
        'NUMBER_OF_DEPENDENT_IN_GOV_SCHOOL',
        'MONTHLY_EDUCATION_EXPENSE',
        'TRANSPORT_EXPENSES',
        'HEALTH_SERVICE_EXPENSE',
        'CALLING_EXPENSE',
        'FOOD_BEVERAGE_EXPENSE',
        'DEPENDENT_EXPENSE',
        'MONTHLY_AID_PARENTS',
        'OTHER_MONTHLY_EXPENSE',
        'KASTLE_USERID',
        'POSTED',
        'POSTING_DATE',
        'ERROR_MESSAGE',
        'CRE_DATE',
        "DOB_NEW",

    ];
}
